TRAIN:
  ANNOTATIONS: "./data/captaincook4d/task_graph_generation_annotations.json"
  TASK_GRAPHS: "./data/captaincook4d/ground_truth_task_graphs"
  ACTIVITY_NAME: "Cheese Pimiento"
  OUTPUT_DIR: "./Experiments"
  SEED: 42
  BETA: 0.005
  EPOCHS: 1000
