TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/blenderbananapancakes/not_used_in_train.json"
  ACTIVITY_NAME: "Blender Banana Pancakes"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/blenderbananapancakes/model_blenderbananapancakes_best.pth
