TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/breakfastburritos/not_used_in_train.json"
  ACTIVITY_NAME: "Breakfast Burritos"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/breakfastburritos/model_breakfastburritos_best.pth
