TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/broccolistirfry/not_used_in_train.json"
  ACTIVITY_NAME: "Broccoli Stir Fry"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/broccolistirfry/model_broccolistirfry_best.pth