TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/buttercorncup/not_used_in_train.json"
  ACTIVITY_NAME: "Butter Corn Cup"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/buttercorncup/model_buttercorncup_best.pth