TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/cheesepimiento/not_used_in_train.json"
  ACTIVITY_NAME: "Cheese Pimiento"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/cheesepimiento/model_cheesepimiento_best.pth