TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/coffee/not_used_in_train.json"
  ACTIVITY_NAME: "Coffee"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/coffee/model_coffee_best.pth