TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/cucumberraita/not_used_in_train.json"
  ACTIVITY_NAME: "Cucumber Raita"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/cucumberraita/model_cucumberraita_best.pth