TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/microwaveeggsandwich/not_used_in_train.json"
  ACTIVITY_NAME: "Microwave Egg Sandwich"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/microwaveeggsandwich/model_microwaveeggsandwich_best.pth