TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/microwavefrenchtoast/not_used_in_train.json"
  ACTIVITY_NAME: "Microwave French Toast"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/microwavefrenchtoast/model_microwavefrenchtoast_best.pth