TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/mugcake/not_used_in_train.json"
  ACTIVITY_NAME: "Mug Cake"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/mugcake/model_mugcake_best.pth