TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/panfriedtofu/not_used_in_train.json"
  ACTIVITY_NAME: "Pan Fried Tofu"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/panfriedtofu/model_panfriedtofu_best.pth