TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/pinwheels/not_used_in_train.json"
  ACTIVITY_NAME: "Pinwheels"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/pinwheels/model_pinwheels_best.pth