TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/ramen/not_used_in_train.json"
  ACTIVITY_NAME: "Ramen"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/ramen/model_ramen_best.pth