TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/spicedhotchocolate/not_used_in_train.json"
  ACTIVITY_NAME: "Spiced Hot Chocolate"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/spicedhotchocolate/model_spicedhotchocolate_best.pth