TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/tomatomozzarellasalad/not_used_in_train.json"
  ACTIVITY_NAME: "Tomato Mozzarella Salad"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/tomatomozzarellasalad/model_tomatomozzarellasalad_best.pth