TRAIN:
  ANNOTATIONS: "../TGT/Experiments-TGT-video-model/zoodles/not_used_in_train.json"
  ACTIVITY_NAME: "Zoodles"
  EMBEDDINGS: "../../data/captaincook4d/video_and_text_feature"
  MODEL: ../TGT/Experiments-TGT-video-model/zoodles/model_zoodles_best.pth