DATA:
  KEYSTEPS_JSON_PATH: ../../data/assembly101/train.json
  OUTPUT_PATH: ./Assembly101-O/ILP_acc
  SCRIPT_PATH: ILP.py
  OBJECTIVE: acc # This is the objective function to optimize (acc or prec)
  AUGMENTED: False