DATA:
  KEYSTEPS_JSON_PATH: ../../data/epic-tent/train.json
  OUTPUT_PATH: ./EPIC-Tent-O/ILP_prec
  SCRIPT_PATH: ILP.py
  OBJECTIVE: prec # This is the objective function to optimize (acc or prec)
  AUGMENTED: False