DATA:
  ANNOTATIONS: "../../data/assembly101/test.json"
  PRED_TASK_GRAPHS: "../baselines/Assembly101-O/count_based/graph_assembly101.adjlist"
  OUTPUT_PATH: "./Assembly101-O-GT/count_based"
  SCENARIO_NAME: "assembly101"