TRAIN:
  ANNOTATIONS: "../../data/captaincook4d/task_graph_generation_annotations.json"
  TASK_GRAPHS: "../../data/captaincook4d/ground_truth_task_graphs"
  ACTIVITY_NAME: "Butter Corn Cup"
  OUTPUT_DIR: "./Experiments-TGT-text-model"
  SEED: 42
  EPOCHS: 3000
  EMBEDDINGS: "../../data/captaincook4d/text_feature"